server:
  port: 8763
  context-path: /nessage
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  rabbitmq:
    host: 192.168.136.101
    port: 5672
    username: test
    password: 123456
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: auto
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 80902935@qq.com #QQ邮箱
    password: xrejibjexvvmbhcc #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: 80902935@qq.com #与上面的username保持一致
